"""Tests for clipboard paste injection and clipboard restore.

Nothing here touches the user's clipboard or sends real keystrokes: macOS tests use a private
named pasteboard and a patched event poster, Linux tests a fake xclip/xdotool.
"""

from __future__ import annotations

import os
import subprocess
import sys
import threading
import time
from types import SimpleNamespace
from unittest.mock import MagicMock, patch

import pytest

from vox import injector
from vox.errors import InjectionError
from vox.window import AppType

darwin_only = pytest.mark.skipif(sys.platform != "darwin", reason="NSPasteboard is macOS-only")


# -- macOS -------------------------------------------------------------------------


@pytest.fixture
def pasteboard():
    """A private pasteboard standing in for the general one, and a recorder for Cmd+V."""
    import AppKit

    private = AppKit.NSPasteboard.pasteboardWithUniqueName()
    posted = MagicMock(name="post_cmd_v")
    try:
        with patch.object(injector, "_general_pasteboard", return_value=private), \
             patch.object(injector, "_post_cmd_v", posted), \
             patch.object(injector.time, "sleep"):
            yield SimpleNamespace(pb=private, post=posted)
    finally:
        private.releaseGlobally()


def _items(pb) -> list[dict[str, bytes]]:
    return [{t: bytes(item.dataForType_(t)) for t in item.types()} for item in pb.pasteboardItems() or ()]


def _write_items(pb, *items: dict[str, bytes]) -> None:
    import AppKit
    from Foundation import NSData

    objects = []
    for types in items:
        item = AppKit.NSPasteboardItem.alloc().init()
        for pasteboard_type, data in types.items():
            item.setData_forType_(NSData.dataWithBytes_length_(data, len(data)), pasteboard_type)
        objects.append(item)
    pb.clearContents()
    assert pb.writeObjects_(objects)


@darwin_only
def test_macos_paste_restores_text_clipboard(pasteboard):
    import AppKit

    pasteboard.pb.clearContents()
    pasteboard.pb.setString_forType_("what I copied", AppKit.NSPasteboardTypeString)
    during = {}
    pasteboard.post.side_effect = lambda: during.update(text=pasteboard.pb.stringForType_(AppKit.NSPasteboardTypeString))

    injector.paste("dictated text", AppType.EDITOR)

    pasteboard.post.assert_called_once()
    assert during["text"] == "dictated text"
    assert pasteboard.pb.stringForType_(AppKit.NSPasteboardTypeString) == "what I copied"


@darwin_only
def test_macos_paste_restores_images_files_and_every_item(pasteboard):
    """A screenshot plus a copied file come back with every type and byte intact."""
    original = (
        {"public.png": b"\x89PNG\r\n\x1a\nimage", "public.utf8-plain-text": b"caption"},
        {"public.file-url": b"file:///Users/me/report.pdf"},
    )
    _write_items(pasteboard.pb, *original)

    injector.paste("dictated", AppType.CHAT)

    assert _items(pasteboard.pb) == list(original)


@darwin_only
def test_macos_paste_keeps_password_manager_markers(pasteboard):
    concealed = {"public.utf8-plain-text": b"hunter2", "org.nspasteboard.ConcealedType": b""}
    _write_items(pasteboard.pb, concealed)

    injector.paste("dictated", AppType.BROWSER)

    assert _items(pasteboard.pb) == [concealed]


@darwin_only
def test_macos_empty_clipboard_is_cleared_after_paste(pasteboard):
    """The dictation does not linger on a clipboard that was empty before."""
    pasteboard.pb.clearContents()

    injector.paste("dictated", AppType.EDITOR)

    assert _items(pasteboard.pb) == []


@darwin_only
def test_macos_dictation_write_is_transient_and_user_copy_is_not(pasteboard):
    """Clipboard managers skip the paste-only write; an explicit Copy stays a normal copy."""
    types_during_paste = []
    pasteboard.post.side_effect = lambda: types_during_paste.extend(pasteboard.pb.types())

    injector.paste("dictated", AppType.EDITOR)
    assert {"org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"} <= set(types_during_paste)

    injector.set_clipboard("copied from history")
    assert "org.nspasteboard.TransientType" not in pasteboard.pb.types()


@darwin_only
def test_macos_restore_waits_after_paste(pasteboard):
    """The restore waits long enough for a busy app to read the dictation first."""
    import AppKit

    pasteboard.pb.clearContents()
    pasteboard.pb.setString_forType_("original", AppKit.NSPasteboardTypeString)
    at_sleep = []
    injector.time.sleep.side_effect = lambda seconds: at_sleep.append(
        (seconds, pasteboard.pb.stringForType_(AppKit.NSPasteboardTypeString))
    )

    injector.paste("dictated", AppType.EDITOR)

    assert at_sleep == [(injector._MACOS_RESTORE_DELAY, "dictated")]
    assert injector._MACOS_RESTORE_DELAY >= 0.3


@darwin_only
def test_macos_copy_during_paste_is_not_overwritten(pasteboard):
    """If the user copies something while Vox waits, that newer copy wins over the restore."""
    import AppKit

    pasteboard.pb.clearContents()
    pasteboard.pb.setString_forType_("original", AppKit.NSPasteboardTypeString)
    injector.time.sleep.side_effect = lambda seconds: injector.set_clipboard("copied meanwhile")

    injector.paste("dictated", AppType.EDITOR)

    assert pasteboard.pb.stringForType_(AppKit.NSPasteboardTypeString) == "copied meanwhile"


@darwin_only
def test_macos_paste_failure_restores_and_raises(pasteboard):
    import AppKit

    pasteboard.pb.clearContents()
    pasteboard.pb.setString_forType_("original", AppKit.NSPasteboardTypeString)
    pasteboard.post.side_effect = InjectionError("no accessibility")

    with pytest.raises(InjectionError):
        injector.paste("dictated", AppType.EDITOR)

    assert pasteboard.pb.stringForType_(AppKit.NSPasteboardTypeString) == "original"


@darwin_only
def test_macos_paste_from_worker_thread(pasteboard):
    """The daemon pastes via asyncio.to_thread; the pasteboard work must hold up off the main thread."""
    import AppKit

    pasteboard.pb.clearContents()
    pasteboard.pb.setString_forType_("original", AppKit.NSPasteboardTypeString)
    errors = []

    def work():
        try:
            injector.paste("dictated", AppType.EDITOR)
        except Exception as e:  # surfaced below
            errors.append(e)

    thread = threading.Thread(target=work)
    thread.start()
    thread.join(timeout=10)

    assert not errors
    pasteboard.post.assert_called_once()
    assert pasteboard.pb.stringForType_(AppKit.NSPasteboardTypeString) == "original"


@darwin_only
def test_set_clipboard_writes_plain_copy(pasteboard):
    import AppKit

    injector.set_clipboard("recovered dictation ✓")
    assert pasteboard.pb.stringForType_(AppKit.NSPasteboardTypeString) == "recovered dictation ✓"


@darwin_only
def test_macos_cmd_v_posts_layout_keycode_with_command_flag(monkeypatch):
    import Quartz

    created, flagged, posted = [], [], []
    monkeypatch.setattr(Quartz, "CGEventCreateKeyboardEvent", lambda src, key, down: created.append((src, key, down)) or (key, down))
    monkeypatch.setattr(Quartz, "CGEventSetFlags", lambda event, flags: flagged.append((event, flags)))
    monkeypatch.setattr(Quartz, "CGEventPost", lambda tap, event: posted.append((tap, event)))
    monkeypatch.setattr(injector, "_paste_keycode", lambda: 47)

    injector._post_cmd_v()

    assert created == [(None, 47, True), (None, 47, False)]
    assert [flags for _, flags in flagged] == [Quartz.kCGEventFlagMaskCommand] * 2
    assert posted == [(Quartz.kCGHIDEventTap, (47, True)), (Quartz.kCGHIDEventTap, (47, False))]


@darwin_only
def test_macos_cmd_v_failure_raises_injection_error(monkeypatch):
    import Quartz

    def fail(*args):
        raise RuntimeError("event tap refused")

    monkeypatch.setattr(Quartz, "CGEventPost", fail)
    with pytest.raises(InjectionError, match="event tap refused"):
        injector._post_cmd_v()


def _fake_layout(monkeypatch, mapping: dict[int, str]):
    """Patch pynput's layout helpers: keycode -> character typed with Command held."""
    import contextlib

    darwin_util = SimpleNamespace(
        keycode_context=lambda: contextlib.nullcontext("layout"),
        keycode_to_string=lambda context, keycode, modifiers=0: mapping.get(keycode, "") if modifiers == injector._CMD_KEY_STATE else "",
    )
    monkeypatch.setitem(sys.modules, "pynput._util.darwin", darwin_util)


def test_paste_keycode_follows_dvorak(monkeypatch):
    _fake_layout(monkeypatch, {9: "k", 47: "v"})
    assert injector._paste_keycode() == 47


def test_paste_keycode_falls_back_to_ansi_v_without_latin_v(monkeypatch):
    """A Cyrillic layout has no "v": paste with the physical V key, never keycode 0 (Cmd+A)."""
    _fake_layout(monkeypatch, {0: "ф", 9: "м"})
    assert injector._paste_keycode() == 9


def test_paste_keycode_falls_back_when_lookup_fails(monkeypatch):
    def broken():
        raise OSError("no input source")

    monkeypatch.setitem(sys.modules, "pynput._util.darwin", SimpleNamespace(keycode_context=broken, keycode_to_string=None))
    assert injector._paste_keycode() == 9


@darwin_only
def test_paste_keycode_reads_the_real_layout_off_the_main_thread():
    """Read-only lookup of the active layout from a worker thread, as a paste does."""
    result = []
    thread = threading.Thread(target=lambda: result.append(injector._paste_keycode()))
    thread.start()
    thread.join(timeout=10)
    assert result and 0 <= result[0] < 128


def test_pastes_are_serialized_across_threads(monkeypatch):
    """A paste still finishing in a cancelled worker thread must restore before the next one starts."""
    inside = threading.Event()
    release = threading.Event()
    order = []

    def slow_paste(text, app_type):
        order.append(f"start {text}")
        if text == "first":
            inside.set()
            release.wait(5)
        order.append(f"end {text}")

    monkeypatch.setattr(injector, "_paste_macos", slow_paste)
    monkeypatch.setattr(injector, "_paste_linux", slow_paste)

    first = threading.Thread(target=injector.paste, args=("first",))
    first.start()
    assert inside.wait(5)
    second = threading.Thread(target=injector.paste, args=("second",))
    second.start()
    time.sleep(0.05)
    assert order == ["start first"]
    release.set()
    first.join(5)
    second.join(5)
    assert order == ["start first", "end first", "start second", "end second"]


# -- Linux (X11) -------------------------------------------------------------------


class FakeOwnerProcess:
    """A stand-in for the foreground `xclip -quiet` that owns CLIPBOARD during the paste."""

    def __init__(self, fail: bool = False) -> None:
        read_fd, self._write_fd = os.pipe()
        self.stderr = os.fdopen(read_fd, "rb", buffering=0)
        self.stdin = SimpleNamespace(data=b"", write=self._stdin_write, close=lambda: None)
        self.returncode = None
        self.served = 0
        self.terminated = False
        if fail:
            self._say(b"Error: Can't open display: (null)\n")
            self._exit(1)
        else:
            self._say(b"  Waiting for selection request number 1\n")

    def _stdin_write(self, data: bytes) -> None:
        self.stdin.data += data

    def _say(self, line: bytes) -> None:
        if self._write_fd is not None:
            os.write(self._write_fd, line)

    def _exit(self, code: int) -> None:
        if self.returncode is None:
            self.returncode = code
        if self._write_fd is not None:
            os.close(self._write_fd)
            self._write_fd = None

    def serve(self, count: int = 1) -> None:
        for _ in range(count):
            self.served += 1
            self._say(f"  Waiting for selection request number {self.served + 1}\n".encode())

    def lose_selection(self) -> None:
        """Another client took CLIPBOARD: xclip exits."""
        self._exit(0)

    def poll(self):
        return self.returncode

    def terminate(self) -> None:
        self.terminated = True
        self._exit(-15)

    def kill(self) -> None:
        self._exit(-9)

    def wait(self, timeout=None):
        return self.returncode


class FakeX11:
    """Fake xclip/xdotool: a CLIPBOARD owner offering `clipboard` (target -> bytes), or nothing."""

    def __init__(self, clipboard: dict[str, bytes] | None = None, owner_fails: bool = False) -> None:
        self.clipboard = clipboard
        self.owner_fails = owner_fails
        self.owner: FakeOwnerProcess | None = None
        self.read_error: Exception | None = None
        self.keys_error: Exception | None = None
        self.writes: list[tuple[str | None, bytes]] = []
        self.events: list[str] = []
        self.on_paste = lambda: self.owner.serve(2)  # TARGETS, then the text
        self.xtest = MagicMock(side_effect=self._paste)

    def _paste(self) -> None:
        self.events.append("paste")
        self.on_paste()

    def popen(self, args, **kwargs):
        assert args == ["xclip", "-quiet", "-selection", "clipboard"]
        self.owner = FakeOwnerProcess(fail=self.owner_fails)
        return self.owner

    def run(self, args, **kwargs):
        assert kwargs.get("timeout"), f"{args[0]} runs without a timeout"
        assert not kwargs.get("shell")
        if args[0] == "xdotool":
            self.events.append(f"keys {args[-1]}")
            if self.keys_error is not None:
                raise self.keys_error
            self._paste()
            return subprocess.CompletedProcess(args, 0)
        assert args[:3] == ["xclip", "-selection", "clipboard"]
        target = args[args.index("-t") + 1] if "-t" in args else None
        if "-o" in args:
            if self.read_error is not None:
                raise self.read_error
            if self.clipboard is None or (target != "TARGETS" and target not in self.clipboard):
                raise subprocess.CalledProcessError(1, args)
            data = b"TARGETS\n" + b"".join(t.encode() + b"\n" for t in self.clipboard) if target == "TARGETS" else self.clipboard[target]
            return subprocess.CompletedProcess(args, 0, stdout=data, stderr=b"")
        # A write: the new background xclip takes the selection from the paste's owner
        assert kwargs.get("stdout") == subprocess.DEVNULL and kwargs.get("stderr") == subprocess.DEVNULL
        self.events.append("restore")
        self.writes.append((target, kwargs["input"]))
        if self.owner is not None:
            self.owner.lose_selection()
        return subprocess.CompletedProcess(args, 0)


@pytest.fixture
def x11(monkeypatch):
    fake = FakeX11()
    monkeypatch.setattr(sys, "platform", "linux")
    monkeypatch.setattr(injector.subprocess, "run", fake.run)
    monkeypatch.setattr(injector.subprocess, "Popen", fake.popen)
    monkeypatch.setattr(injector, "_xtest_ctrl_v", fake.xtest)
    monkeypatch.setattr(injector.time, "sleep", lambda seconds: None)
    monkeypatch.setattr(injector, "_X11_REQUEST_TIMEOUT", 0.2)
    monkeypatch.setattr(injector, "_X11_FOLLOW_UP_TIMEOUT", 0.05)
    return fake


def test_linux_paste_restores_clipboard_bytes_exactly(x11):
    """Latin-1 bytes and CRLF line endings survive: the clipboard is never decoded."""
    x11.clipboard = {"UTF8_STRING": b"caf\xe9\r\nline two", "STRING": b"caf\xe9\r\nline two"}

    injector.paste("dictated text", AppType.EDITOR)

    assert x11.owner.stdin.data == b"dictated text"
    assert x11.events == ["keys ctrl+v", "paste", "restore"]
    assert x11.writes == [("UTF8_STRING", b"caf\xe9\r\nline two")]
    assert x11.owner.returncode is not None


def test_linux_terminal_pastes_with_ctrl_shift_v(x11):
    x11.clipboard = {"UTF8_STRING": b"x"}
    injector.paste("ls -la", AppType.TERMINAL)
    assert x11.events[0] == "keys ctrl+shift+v"


def test_linux_other_app_pastes_via_xtest_and_restores(x11):
    """Unclassified apps get the XTest keystroke but the same full clipboard restore."""
    x11.clipboard = {"UTF8_STRING": b"what I copied"}

    injector.paste("dictated", AppType.OTHER)

    x11.xtest.assert_called_once()
    assert not any(e.startswith("keys") for e in x11.events)
    assert x11.writes == [("UTF8_STRING", b"what I copied")]


@pytest.mark.parametrize(("clipboard", "restored"), [
    ({"image/png": b"\x89PNG", "image/bmp": b"BM"}, ("image/png", b"\x89PNG")),
    ({"image/jpeg": b"\xff\xd8"}, ("image/jpeg", b"\xff\xd8")),
    ({"text/html": b"<b>hi</b>"}, ("text/html", b"<b>hi</b>")),
    # Plain text wins over HTML: xclip serves one target, and every app can paste text
    ({"text/html": b"<b>hi</b>", "UTF8_STRING": b"hi"}, ("UTF8_STRING", b"hi")),
    # Copied files paste back as files
    ({"x-special/gnome-copied-files": b"copy\nfile:///tmp/a.txt", "text/uri-list": b"file:///tmp/a.txt\r\n",
      "UTF8_STRING": b"/tmp/a.txt"}, ("text/uri-list", b"file:///tmp/a.txt\r\n")),
    # A copied web link is better restored as text
    ({"text/uri-list": b"https://example.com/\r\n", "UTF8_STRING": b"https://example.com/"}, ("UTF8_STRING", b"https://example.com/")),
    ({"STRING": b"legacy"}, ("STRING", b"legacy")),
])
def test_linux_restores_the_most_useful_target(x11, clipboard, restored):
    x11.clipboard = clipboard
    injector.paste("dictated", AppType.EDITOR)
    assert x11.writes == [restored]


def test_linux_empty_clipboard_is_left_empty(x11):
    """Nothing to restore: stopping the paste's xclip drops the dictation from the clipboard."""
    x11.clipboard = None

    injector.paste("dictated", AppType.EDITOR)

    assert x11.writes == []
    assert x11.owner.terminated


@pytest.mark.parametrize("error", [subprocess.TimeoutExpired(["xclip"], 1), FileNotFoundError("xclip")])
def test_linux_unreadable_clipboard_still_pastes(x11, error):
    """A hung or missing clipboard owner must not stop the paste (or block forever)."""
    x11.clipboard = {"UTF8_STRING": b"x"}
    x11.read_error = error

    injector.paste("dictated", AppType.EDITOR)

    assert x11.events == ["keys ctrl+v", "paste"]
    assert x11.writes == []


def test_linux_restore_waits_for_the_target_to_fetch_the_text(x11):
    """A slow app asks for the text late; the restore must come after that, not after a fixed 50 ms."""
    x11.clipboard = {"UTF8_STRING": b"original"}

    def slow_target():
        def serve():
            x11.events.append("target fetched")
            x11.owner.serve(2)

        threading.Timer(0.1, serve).start()

    x11.on_paste = slow_target

    injector.paste("dictated", AppType.EDITOR)

    assert x11.events == ["keys ctrl+v", "paste", "target fetched", "restore"]


def test_linux_requests_before_the_keystroke_do_not_count(x11, monkeypatch):
    """A clipboard manager fetching the text as soon as it is copied is not the target pasting it."""
    x11.clipboard = {"UTF8_STRING": b"original"}

    def popen_with_manager(args, **kwargs):
        owner = x11.popen(args, **kwargs)
        owner.serve(2)  # the manager's TARGETS and text requests
        return owner

    def target_fetches_later():
        def serve():
            x11.events.append("target fetched")
            x11.owner.serve(2)

        threading.Timer(0.05, serve).start()

    monkeypatch.setattr(injector.subprocess, "Popen", popen_with_manager)
    x11.on_paste = target_fetches_later

    injector.paste("dictated", AppType.EDITOR)

    assert x11.events == ["keys ctrl+v", "paste", "target fetched", "restore"]


def test_linux_restore_goes_ahead_when_the_target_never_asks(x11):
    x11.clipboard = {"UTF8_STRING": b"original"}
    x11.on_paste = lambda: None

    started = time.monotonic()
    injector.paste("dictated", AppType.EDITOR)

    assert x11.writes == [("UTF8_STRING", b"original")]
    assert time.monotonic() - started < 2


def test_linux_copy_during_paste_is_not_overwritten(x11):
    """Another client took the clipboard while Vox waited: its contents win over the restore."""
    x11.clipboard = {"UTF8_STRING": b"original"}
    x11.on_paste = lambda: x11.owner.lose_selection()

    injector.paste("dictated", AppType.EDITOR)

    assert x11.writes == []


@pytest.mark.parametrize("app_type", [AppType.EDITOR, AppType.OTHER])
def test_linux_xclip_failure_raises_and_never_pastes(x11, app_type):
    """If the dictation never reached the clipboard, pressing paste would paste the old contents."""
    x11.clipboard = {"UTF8_STRING": b"a password"}
    x11.owner_fails = True

    with pytest.raises(InjectionError, match="Can't open display"):
        injector.paste("dictated", app_type)

    assert "paste" not in x11.events
    x11.xtest.assert_not_called()
    assert x11.writes == []


def test_linux_missing_xclip_raises(x11, monkeypatch):
    def missing(args, **kwargs):
        raise FileNotFoundError("xclip")

    monkeypatch.setattr(injector.subprocess, "Popen", missing)
    with pytest.raises(InjectionError, match="xclip"):
        injector.paste("dictated", AppType.EDITOR)


@pytest.mark.parametrize("error", [
    subprocess.CalledProcessError(1, ["xdotool"]),
    subprocess.TimeoutExpired(["xdotool"], 2),
    FileNotFoundError("xdotool"),
])
def test_linux_keystroke_failure_raises_and_restores(x11, error):
    x11.clipboard = {"UTF8_STRING": b"original"}
    x11.keys_error = error

    with pytest.raises(InjectionError, match="xdotool paste failed"):
        injector.paste("dictated", AppType.BROWSER)

    assert x11.writes == [("UTF8_STRING", b"original")]


def test_linux_xtest_failure_raises_and_restores(x11):
    x11.clipboard = {"UTF8_STRING": b"original"}
    x11.xtest.side_effect = OSError("no display")

    with pytest.raises(InjectionError, match="Xlib paste failed"):
        injector.paste("dictated", AppType.OTHER)

    assert x11.writes == [("UTF8_STRING", b"original")]


def test_linux_paste_from_worker_thread(x11):
    x11.clipboard = {"UTF8_STRING": b"original"}
    errors = []

    def work():
        try:
            injector.paste("dictated", AppType.EDITOR)
        except Exception as e:  # surfaced below
            errors.append(e)

    thread = threading.Thread(target=work)
    thread.start()
    thread.join(timeout=10)
    assert not errors
    assert x11.writes == [("UTF8_STRING", b"original")]


def test_linux_set_clipboard_is_a_plain_copy(x11):
    injector.set_clipboard("from history ✓")
    assert x11.writes == [(None, "from history ✓".encode())]


@pytest.mark.parametrize("error", [subprocess.CalledProcessError(1, ["xclip"]), subprocess.TimeoutExpired(["xclip"], 2)])
def test_linux_set_clipboard_failure_raises(monkeypatch, error):
    monkeypatch.setattr(sys, "platform", "linux")
    monkeypatch.setattr(injector.subprocess, "run", MagicMock(side_effect=error))
    with pytest.raises(InjectionError):
        injector.set_clipboard("text")


def test_clipboard_owner_counts_requests_split_across_reads(monkeypatch):
    """xclip's progress lines can arrive in pieces; the count must still be right."""
    process = FakeOwnerProcess()
    monkeypatch.setattr(injector.subprocess, "Popen", lambda *a, **k: process)
    owner = injector._ClipboardOwner(b"text")
    assert owner.wait_served(0, 1)
    assert owner.served == 0

    process._say(b"  Waiting for selection req")
    assert not owner.wait_served(1, 0.05)
    process._say(b"uest number 2\n  Waiting for selection request number 3\n")
    assert owner.wait_served(2, 1)
    assert owner.served == 2

    process.lose_selection()
    assert not owner.wait_served(3, 1)
    assert owner.exited()
    owner.close()
