"""Text injection: put the text on the clipboard, press paste, then restore the user's clipboard."""

from __future__ import annotations

import logging
import os
import re
import select
import shutil
import subprocess
import sys
import threading
import time
from dataclasses import dataclass

from .errors import DependencyError, InjectionError
from .window import AppType

log = logging.getLogger(__name__)

# One paste at a time: a cancelled paste still running in its worker thread must finish
# restoring the clipboard before the next one snapshots it.
_paste_lock = threading.Lock()

# macOS cannot tell when the target has read the pasteboard, so the restore waits this long
# after Cmd+V. 50 ms was too short for a busy app, which then pasted the old clipboard.
_MACOS_RESTORE_DELAY = 0.5

# nspasteboard.org markers: clipboard managers skip the dictation Vox writes only to paste it
_TRANSIENT_TYPES = ("org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType")
# What password managers mark a copied password with (nspasteboard.org); it goes back for this Mac only
_CONCEALED_TYPE = "org.nspasteboard.ConcealedType"

_KVK_ANSI_V = 9
_CMD_KEY_STATE = 1  # Carbon cmdKey >> 8, the modifier state UCKeyTranslate expects

# X11: how long the target gets to request the text after the paste keystroke before the
# restore goes ahead anyway (a slow app, or a window that ignores the paste).
_X11_REQUEST_TIMEOUT = 1.0
# A target fetches the text once (xclip does not count TARGETS requests). This grace covers an
# app that asks twice (xclip also counts a refused request for a target it does not offer), or a
# clipboard manager's late fetch that was counted as the target's. It delays only the restore.
_X11_FOLLOW_UP_TIMEOUT = 0.5
_TOOL_TIMEOUT = 2.0

# X11 restore preference. xclip serves one target, so a clipboard that offered several comes
# back as one: copied files as a uri-list, then plain text, because every app can paste it
# (restoring text/html alone would leave terminals and plain text fields with nothing to paste),
# then an image or HTML when there is no text.
_X11_TEXT_TARGETS = ("UTF8_STRING", "text/plain;charset=utf-8", "STRING", "TEXT", "text/plain")
_X11_RICH_TARGETS = ("image/png", "text/html")
_X11_PASSWORD_HINT = "x-kde-passwordManagerHint"


def check_accessibility_permission(prompt: bool = False) -> bool:
    """Check if current process has macOS Accessibility permissions via AXIsProcessTrusted."""
    if sys.platform != "darwin":
        return True
    from ApplicationServices import AXIsProcessTrusted, AXIsProcessTrustedWithOptions, kAXTrustedCheckOptionPrompt

    if prompt:
        return bool(AXIsProcessTrustedWithOptions({kAXTrustedCheckOptionPrompt: True}))
    return bool(AXIsProcessTrusted())


def check_dependencies() -> None:
    """Check that required system dependencies are installed."""
    if sys.platform == "darwin":
        if not shutil.which("osascript"):
            raise DependencyError("Missing system dependency: osascript")
        return

    if not shutil.which("xprop"):
        # Vox still works, but window detection reads WM_CLASS through xprop
        log.warning(
            "xprop is not installed, so Vox can't tell which app is focused: it pastes into terminals with "
            "Ctrl+V, which they ignore, and [window_classes] doesn't apply. Install with: sudo apt install x11-utils"
        )
    missing = []
    if not shutil.which("xdotool"):
        missing.append("xdotool")
    if not shutil.which("xclip"):
        missing.append("xclip")
    if missing:
        raise DependencyError(
            f"Missing system dependencies: {', '.join(missing)}. "
            f"Install with: sudo apt install {' '.join(missing)}"
        )


def set_clipboard(text: str) -> None:
    """Copy text to the clipboard as a normal copy (the user's own Copy action)."""
    if sys.platform == "darwin":
        try:
            from AppKit import NSPasteboardTypeString

            pb = _general_pasteboard()
            pb.clearContents()
            pb.setString_forType_(text, NSPasteboardTypeString)
            return
        except Exception as e:
            raise InjectionError(f"Failed to set NSPasteboard: {e}") from e
    _x11_write(text.encode())


def paste(text: str, app_type: AppType = AppType.OTHER) -> None:
    """Paste text at the cursor, then put the user's clipboard back. Safe to call from a worker thread."""
    with _paste_lock:
        if sys.platform == "darwin":
            _paste_macos(text, app_type)
        else:
            _paste_linux(text, app_type)


# -- macOS -------------------------------------------------------------------------


def _general_pasteboard():
    from AppKit import NSPasteboard

    return NSPasteboard.generalPasteboard()


def _paste_macos(text: str, app_type: AppType) -> None:
    import objc

    # A long-lived worker thread has no autorelease pool of its own
    with objc.autorelease_pool():
        pb = _general_pasteboard()
        saved = _snapshot_pasteboard(pb)
        written: int | None = None
        try:
            written = _write_transient(pb, text)
            _post_cmd_v()
            log.debug("Injected %d chars via Cmd+V on macOS (app_type=%s)", len(text), app_type.value)
            time.sleep(_MACOS_RESTORE_DELAY)
        finally:
            _restore_pasteboard(pb, saved, written)


def _snapshot_pasteboard(pb) -> list[dict] | None:
    """Every item with the data of every type it offers; None when it could not be read."""
    started = time.monotonic()
    try:
        saved = [
            {t: data for t in item.types() if (data := item.dataForType_(t)) is not None}
            for item in pb.pasteboardItems() or ()
        ]
    except Exception:
        log.warning("Failed to read the clipboard; it will not be restored", exc_info=True)
        return None
    # Reading every type makes the source app render the ones it provides lazily (PDF, TIFF...)
    log.debug(
        "Saved %d clipboard types in %.0f ms",
        sum(len(types) for types in saved), (time.monotonic() - started) * 1000,
    )
    return saved


def _write_transient(pb, text: str) -> int:
    """Write the dictation for this Mac only, marked transient. Returns the pasteboard's changeCount.

    The text and its markers go in one item and one write, markers first: the pasteboard publishes
    an item's types one at a time in the order they were set, so a clipboard manager polling
    during the write would otherwise see the text without the markers, and record it.
    """
    try:
        from AppKit import NSPasteboardContentsCurrentHostOnly, NSPasteboardItem, NSPasteboardTypeString
        from Foundation import NSData

        item = NSPasteboardItem.alloc().init()
        for marker in _TRANSIENT_TYPES:
            item.setData_forType_(NSData.data(), marker)
        item.setString_forType_(text, NSPasteboardTypeString)
        pb.prepareForNewContentsWithOptions_(NSPasteboardContentsCurrentHostOnly)
        if not pb.writeObjects_([item]):
            raise InjectionError("NSPasteboard refused the text")
        return pb.changeCount()
    except InjectionError:
        raise
    except Exception as e:
        raise InjectionError(f"Failed to set NSPasteboard: {e}") from e


def _restore_pasteboard(pb, saved: list[dict] | None, written: int | None) -> None:
    if saved is None:
        return
    if written is not None and pb.changeCount() != written:
        log.debug("Clipboard changed during the paste; keeping the newer contents")
        return
    try:
        from AppKit import NSPasteboardItem

        items = []
        for types in saved:
            item = NSPasteboardItem.alloc().init()
            for pasteboard_type, data in types.items():
                item.setData_forType_(data, pasteboard_type)
            items.append(item)
        # An empty snapshot still clears, so the dictation does not linger on the clipboard
        cleared = _clear_for_restore(pb, saved)
        if items and not pb.writeObjects_(items):
            _restore_text_only(pb, saved, cleared)
    except Exception:
        log.warning("Failed to restore clipboard", exc_info=True)


def _is_concealed(saved: list[dict]) -> bool:
    return any(_CONCEALED_TYPE in types for types in saved)


def _clear_for_restore(pb, saved: list[dict]) -> int:
    """Clear the pasteboard for the restore; returns its changeCount.

    A password manager's concealed copy is restored for this Mac only: written back as an ordinary
    copy, Universal Clipboard would offer the password to the user's other devices.
    """
    if _is_concealed(saved):
        from AppKit import NSPasteboardContentsCurrentHostOnly

        return pb.prepareForNewContentsWithOptions_(NSPasteboardContentsCurrentHostOnly)
    return pb.clearContents()


def _restore_text_only(pb, saved: list[dict], cleared: int) -> None:
    """The pasteboard refused the full snapshot: put back at least its plain text."""
    from AppKit import NSPasteboardTypeString

    if pb.changeCount() != cleared:
        log.debug("Clipboard changed during the restore; keeping the newer contents")
        return
    text = next((types[NSPasteboardTypeString] for types in saved if NSPasteboardTypeString in types), None)
    _clear_for_restore(pb, saved)
    if text is not None and _is_concealed(saved):
        from Foundation import NSData

        pb.setData_forType_(NSData.data(), _CONCEALED_TYPE)  # before the text, so no manager sees it unmarked
    if text is not None and pb.setData_forType_(text, NSPasteboardTypeString):
        log.warning("The clipboard refused its saved contents; restored only its text")
    else:
        log.warning("The clipboard refused its saved contents; it was left empty")


def _paste_keycode() -> int:
    """The key that types "v" with Command held in the current layout (Dvorak moves it).

    Looked up on every paste because the user can switch layouts at any time. Layouts without
    a "v" (Cyrillic, Greek) paste with the ANSI V key, as macOS itself does for Cmd shortcuts.
    """
    try:
        from pynput._util.darwin import keycode_context, keycode_to_string

        with keycode_context() as context:
            for keycode in range(128):
                if keycode_to_string(context, keycode, _CMD_KEY_STATE) == "v":
                    return keycode
    except Exception:
        log.debug("Keyboard layout lookup failed; pasting with the ANSI V key", exc_info=True)
    return _KVK_ANSI_V


def _post_cmd_v() -> None:
    try:
        from Quartz import CGEventCreateKeyboardEvent, CGEventPost, CGEventSetFlags, kCGEventFlagMaskCommand, kCGHIDEventTap

        keycode = _paste_keycode()
        for key_down in (True, False):
            event = CGEventCreateKeyboardEvent(None, keycode, key_down)
            CGEventSetFlags(event, kCGEventFlagMaskCommand)
            CGEventPost(kCGHIDEventTap, event)
    except Exception as e:
        raise InjectionError(f"macOS paste simulation failed: {e}") from e


# -- Linux (X11) -------------------------------------------------------------------


@dataclass
class _Selection:
    target: str
    data: bytes


def _paste_linux(text: str, app_type: AppType) -> None:
    saved = _x11_snapshot()
    try:
        owner = _ClipboardOwner(text.encode())
    except OSError as e:
        raise InjectionError(f"Failed to run xclip: {e}") from e
    try:
        if not owner.wait_served(0, _TOOL_TIMEOUT):
            raise InjectionError(f"Failed to set clipboard via xclip: {owner.error()}")
        # Lets xclip's ownership request reach the server, and clipboard managers fetch the new
        # contents; only requests after the keystroke count as the target's
        time.sleep(0.05)
        owner.drain()
        before = owner.served
        _send_paste_keys(app_type)
        log.debug("Injected %d chars (app_type=%s)", len(text), app_type.value)
        # Restore only once the target has fetched the text, or it pastes the old clipboard
        if owner.wait_served(before + 1, _X11_REQUEST_TIMEOUT):
            owner.wait_served(before + 2, _X11_FOLLOW_UP_TIMEOUT)
        else:
            log.debug("No clipboard request within %.1fs of the paste keystroke", _X11_REQUEST_TIMEOUT)
    finally:
        _x11_restore(owner, saved)


def _send_paste_keys(app_type: AppType) -> None:
    if app_type == AppType.OTHER:
        # Games and unknown apps: XTest, because xdotool's --clearmodifiers breaks some of them
        try:
            _xtest_ctrl_v()
        except Exception as e:
            raise InjectionError(f"Xlib paste failed: {e}") from e
        return
    keys = "ctrl+shift+v" if app_type == AppType.TERMINAL else "ctrl+v"
    try:
        subprocess.run(
            ["xdotool", "key", "--clearmodifiers", keys],
            check=True, stderr=subprocess.DEVNULL, timeout=_TOOL_TIMEOUT,
        )
    except (subprocess.SubprocessError, OSError) as e:
        raise InjectionError(f"xdotool paste failed: {e}") from e


def _xtest_ctrl_v() -> None:
    """Send Ctrl+V via XTest fake input events on a connection of this thread's own."""
    from Xlib import XK, X
    from Xlib.display import Display
    from Xlib.ext import xtest

    d = Display()
    try:
        ctrl = d.keysym_to_keycode(XK.XK_Control_L)
        v = d.keysym_to_keycode(XK.XK_v)
        for event_type, keycode in ((X.KeyPress, ctrl), (X.KeyPress, v), (X.KeyRelease, v), (X.KeyRelease, ctrl)):
            xtest.fake_input(d, event_type, keycode)
        d.sync()
    finally:
        d.close()


class _ClipboardOwner:
    """A foreground `xclip -quiet` that owns CLIPBOARD and reports each request it serves.

    Before every wait xclip prints "Waiting for selection request number N" on stderr, so N - 1
    requests for the data have been served (TARGETS requests are answered but not counted).
    It exits once another client takes the selection.
    """

    _REQUEST = re.compile(rb"selection request number (\d+)")

    def __init__(self, data: bytes) -> None:
        self._proc = subprocess.Popen(
            ["xclip", "-quiet", "-selection", "clipboard"],
            stdin=subprocess.PIPE, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE,
        )
        self._output = b""
        self._eof = False  # xclip closes stderr only by exiting
        self.served = -1  # 0 once xclip owns the selection
        try:
            self._proc.stdin.write(data)
            self._proc.stdin.close()
        except OSError:
            pass  # xclip already exited; wait_served() reports it

    def wait_served(self, count: int, timeout: float) -> bool:
        """Wait until `count` requests have been served. False on timeout or when xclip exits."""
        deadline = time.monotonic() + timeout
        while self.served < count:
            if not self._read(max(0.0, deadline - time.monotonic())):
                return False
        return True

    def drain(self) -> None:
        while self._read(0):
            pass

    def _read(self, timeout: float) -> bool:
        fd = self._proc.stderr.fileno()
        ready, _, _ = select.select([fd], [], [], timeout)
        if not ready:
            return False
        chunk = os.read(fd, 4096)
        if not chunk:
            self._eof = True
            return False
        self._output += chunk
        numbers = self._REQUEST.findall(self._output)
        if numbers:
            self.served = int(numbers[-1]) - 1
        return True

    def exited(self) -> bool:
        # After EOF xclip may not have been reaped yet, and poll() alone would call it alive
        return self._eof or self._proc.poll() is not None

    def error(self) -> str:
        if output := self._output.decode(errors="replace").strip():
            return output
        status = self._proc.poll()
        return "xclip did not take the clipboard in time" if status is None else f"xclip exited with status {status}"

    def close(self) -> None:
        if self._proc.poll() is None:
            self._proc.terminate()
        try:
            self._proc.wait(timeout=1)
        except subprocess.TimeoutExpired:
            self._proc.kill()
            self._proc.wait()
        self._proc.stderr.close()


def _x11_read(target: str, timeout: float) -> bytes | None:
    try:
        return subprocess.run(
            ["xclip", "-selection", "clipboard", "-o", "-t", target],
            capture_output=True, check=True, timeout=timeout,
        ).stdout
    except (subprocess.SubprocessError, OSError) as e:
        log.debug("Could not read clipboard target %s: %s", target, e)
        return None


def _x11_write(data: bytes, target: str | None = None) -> None:
    """Hand data to a background xclip that owns CLIPBOARD until someone else copies."""
    command = ["xclip", "-selection", "clipboard", *(["-t", target] if target else [])]
    try:
        # No pipes on stdout/stderr: the forked xclip keeps them open and run() would wait on it
        subprocess.run(command, input=data, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=_TOOL_TIMEOUT)
    except (subprocess.SubprocessError, OSError) as e:
        raise InjectionError(f"Failed to set clipboard via xclip: {e}") from e


def _x11_snapshot() -> _Selection | None:
    """The clipboard's most useful target as raw bytes, or None when there is nothing to restore."""
    targets = _x11_read("TARGETS", timeout=1.0)
    if not targets:
        return None
    offered = targets.decode("ascii", errors="replace").split()
    if _X11_PASSWORD_HINT in offered and (_x11_read(_X11_PASSWORD_HINT, timeout=_TOOL_TIMEOUT) or b"secret").strip() == b"secret":
        # A password manager's copy (KeePassXC marks it so clipboard histories skip it). xclip can't
        # restore the mark with the text, and unmarked a history would record the password, so the
        # clipboard is left empty, as the password manager's own clear would leave it.
        log.debug("The clipboard holds a password manager's secret; it won't be restored")
        return None
    candidates = ["text/uri-list", *_X11_TEXT_TARGETS, *_X11_RICH_TARGETS]
    candidates += [t for t in offered if t.startswith("image/")]
    has_text = any(t in offered for t in _X11_TEXT_TARGETS)
    for target in dict.fromkeys(c for c in candidates if c in offered):
        data = _x11_read(target, timeout=_TOOL_TIMEOUT)
        if data is None:
            continue
        # Copied files go back as files; a copied web link is better restored as text, if there is any
        if target == "text/uri-list" and has_text and not _only_file_uris(data):
            continue
        return _Selection(target, data)
    log.debug("None of the clipboard targets could be saved: %s", offered)
    return None


def _only_file_uris(uri_list: bytes) -> bool:
    uris = [line for line in uri_list.splitlines() if line and not line.startswith(b"#")]
    return bool(uris) and all(uri.startswith(b"file://") for uri in uris)


def _x11_restore(owner: _ClipboardOwner, saved: _Selection | None) -> None:
    if owner.exited():
        # xclip lost the selection: something was copied during the paste, and that wins
        log.debug("Clipboard changed during the paste; keeping the newer contents")
    elif saved is not None:
        try:
            _x11_write(saved.data, saved.target)
        except InjectionError:
            log.warning("Failed to restore clipboard", exc_info=True)
    # When the clipboard was empty, stopping the owner leaves it empty again
    owner.close()
